import { callAI } from './aiAdapter.js'

const AI_DISCLAIMER = `[DRAFT DOCUMENT — Generated by AI for reference only]
[Verify all details before submitting to EPFO. NOT an official EPFO document.]

`

export async function generateJointDeclaration(user, mismatchData) {
  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  const prompt = `Generate a complete EPFO Joint Declaration form for name correction. Use formal government document language. STRICT RULES: No markdown, no asterisks, no # symbols, no pipe tables (| col | col |). Use plain text only. Use colon-alignment for label-value pairs like "Name in EPF : value". Use blank lines to separate sections. Use a line of dashes (--------) as section separators.

Member Details:
- UAN: ${user.uan}
- Name in EPF Records: ${user.memberName}
- Name in Aadhaar: ${user.aadhaarName}
- Date of Birth: ${user.dob.epf}
- Establishment: ${user.establishmentName}
- Establishment Code: ${user.establishmentCode || 'As per EPFO records'}
- EPFO Regional Office: ${user.epfoRegionalOffice}
- Mismatch Type: ${mismatchData?.mismatchType || 'NAME_DISCREPANCY'}
- Date: ${today}

Generate the complete Joint Declaration with these sections separated by dashes:
1. Heading: EMPLOYEES PROVIDENT FUND ORGANISATION - JOINT DECLARATION FOR CORRECTION OF MEMBER DETAILS
2. Addressee: Regional Provident Fund Commissioner, ${user.epfoRegionalOffice}
3. Date and Subject line mentioning UAN ${user.uan}
4. Joint declaration statement paragraph
5. Discrepancy Details: Name in EPF Record, Name in Aadhaar, Reason — each on its own line with colon alignment
6. Declaration paragraph
7. Supporting Documents to Enclose: numbered plain list
8. Member Signature block (Name, UAN, Signature, Date, Place)
9. Employer Stamp and Signature block

Plain text only. No markdown. No pipe tables.`

  const text = await callAI(prompt, { maxTokens: 1000 })
  return AI_DISCLAIMER + (text || buildFallbackJointDeclaration(user, mismatchData))
}

export async function generateEmployerLetter(user) {
  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  const prompt = `Generate a formal letter from an employee to their previous employer's HR department requesting them to update the exit date in the EPFO UAN Employer Portal.

Employee Details:
- Name: ${user.memberName}
- UAN: ${user.uan}
- Establishment: ${user.establishmentName}
- Date: ${today}

Format as a proper business letter. Plain text only. NO markdown, NO asterisks, NO bold markers.
Include: date, recipient block (To, The HR Manager, ${user.establishmentName}), subject line, 3 paragraphs, professional closing. Under 200 words.`

  const text = await callAI(prompt, { maxTokens: 450 })
  return AI_DISCLAIMER + (text || buildFallbackEmployerLetter(user))
}

export async function generateEPFiGMSComplaint(issueType, user) {
  const issueDesc = {
    NAME:          'Name mismatch between EPF records and Aadhaar — needs Joint Declaration',
    EMPLOYER_EXIT: 'Previous employer has not updated exit date in UAN Employer Portal',
    BANK_KYC:      'Bank account added to UAN but employer approval for KYC is pending',
  }

  const prompt = `Generate a formal complaint for the EPFiGMS portal (EPFO grievance system). Under 150 words. Plain text only — no markdown.

Issue: ${issueDesc[issueType] || issueType}
UAN: ${user.uan}
Member Name: ${user.memberName}
Establishment: ${user.establishmentName}

Include: EPFiGMS complaint category, exact problem, requested action, UAN reference.
Output ONLY the complaint text. No labels, no preamble, no markdown.`

  const text = await callAI(prompt, { maxTokens: 280 })
  return AI_DISCLAIMER + (text || buildFallbackComplaint(issueType, user))
}

function buildFallbackJointDeclaration(user, mismatchData) {
  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  const mismatchLabel = mismatchData?.mismatchType === 'INITIAL_VS_FULL'
    ? 'Initial used instead of full middle name at time of EPF registration'
    : mismatchData?.mismatchType === 'MIDDLE_NAME_MISSING'
    ? 'Middle name/suffix present in EPF record but absent in Aadhaar'
    : 'Name variation between EPF record and Aadhaar'

  return `EMPLOYEES PROVIDENT FUND ORGANISATION
JOINT DECLARATION FOR CORRECTION OF MEMBER DETAILS IN EPF RECORDS

------------------------------------------------------------------------

To,
The Regional Provident Fund Commissioner,
${user.epfoRegionalOffice},
Employees Provident Fund Organisation

Date    : ${today}
Subject : Correction of member name in EPF records for UAN ${user.uan}

------------------------------------------------------------------------

JOINT DECLARATION

We, the undersigned — the Employer and the Member — jointly declare and certify:

Member UAN           : ${user.uan}
Establishment        : ${user.establishmentName}
Establishment Code   : ${user.establishmentCode || 'As per EPFO records'}
EPFO Regional Office : ${user.epfoRegionalOffice}

------------------------------------------------------------------------

NAME DISCREPANCY DETAILS

Name in EPF Records  : ${user.memberName}
Name in Aadhaar      : ${user.aadhaarName}
Reason for Difference: ${mismatchLabel}

------------------------------------------------------------------------

DECLARATION

We jointly declare that "${user.aadhaarName}" as shown in the Aadhaar card is the correct and true name of the member. The name "${user.memberName}" in the EPF records is a variation of the same person. We request the name in EPF records to be corrected to "${user.aadhaarName}".

------------------------------------------------------------------------

SUPPORTING DOCUMENTS TO BE ENCLOSED

1. Self-attested photocopy of Aadhaar card (front and back)
2. Self-attested photocopy of PAN card
3. Additional identity proof showing the correct name (passport, voter ID, or birth certificate)

------------------------------------------------------------------------

MEMBER SIGNATURE

Name      : ${user.aadhaarName}
UAN       : ${user.uan}
Signature : _______________________________
Date      : _______________________________
Place     : _______________________________

------------------------------------------------------------------------

EMPLOYER STAMP & SIGNATURE

Employer Name  : _______________________________
Designation    : _______________________________
Establishment  : ${user.establishmentName}
Est. Code      : ${user.establishmentCode || '_______________'}
Stamp & Sig.   : _______________________________
Date           : _______________________________
Place          : _______________________________

------------------------------------------------------------------------

Note: Submit at your EPFO regional office in person or by registered post with all supporting documents. Retain a copy.
Processing typically takes 15 to 30 days after receipt.`
}

function buildFallbackEmployerLetter(user) {
  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  return `Date: ${today}

To,
The Manager - HR & Payroll,
${user.establishmentName}

Subject: Request to Update Exit Date in EPFO UAN Portal  (UAN: ${user.uan})

Dear Sir / Madam,

I, ${user.memberName}, was employed with your organisation and have since separated from service. However, my exit date has not been updated in the EPFO UAN Employer Portal. This is preventing me from processing my Provident Fund claim (UAN: ${user.uan}).

I request you to kindly update my exit date at the earliest in the UAN Employer Portal (https://unifiedportal-emp.epfindia.gov.in). This update is essential for processing my PF withdrawal claim.

If the update is not made within 15 days from the date of this letter, I will file a grievance on the EPFiGMS portal (https://epfigms.gov.in) under the category "Non-transfer / Exit date not updated".

Thanking you,

${user.memberName}
UAN     : ${user.uan}
Mobile  : ___________________________
Email   : ___________________________`
}

function buildFallbackComplaint(issueType, user) {
  if (issueType === 'EMPLOYER_EXIT') {
    return `Category: Non-transfer / Exit date not updated

I am ${user.memberName} (UAN: ${user.uan}), previously employed at ${user.establishmentName}. My employer has not updated my exit date in the UAN Employer Portal despite my separation from service, preventing me from filing my PF claim.

Requested Action: Please direct ${user.establishmentName} to update my exit date in the UAN Employer Portal so my final settlement claim can be processed.

UAN: ${user.uan}
Establishment: ${user.establishmentName}`
  }
  if (issueType === 'NAME') {
    return `Category: KYC / Name correction required

I am ${user.memberName} (UAN: ${user.uan}). My name in EPF records differs from my Aadhaar name. A Joint Declaration has been initiated with my employer.

Requested Action: Please expedite processing of the name correction Joint Declaration once submitted to the regional office.

UAN: ${user.uan}
Establishment: ${user.establishmentName}`
  }
  return `Category: KYC / Bank account verification pending

I am ${user.memberName} (UAN: ${user.uan}). My bank account is linked to the UAN portal but employer KYC approval is pending, preventing my PF claim.

Requested Action: Please direct the employer to approve bank KYC at the earliest.

UAN: ${user.uan}
Establishment: ${user.establishmentName}`
}
