/**
 * PDF generator — lazy-loads jsPDF so it is NOT included in the initial bundle.
 *
 * Handles:
 *   - Section separators (lines of dashes)
 *   - Label : Value aligned lines (kept as-is)
 *   - Colon-style multi-line headers
 *   - Proper page breaks with header repeat
 */

export async function downloadDocumentAsPDF(content, filename = 'EPFO-Document.pdf') {
  try {
    const { default: jsPDF } = await import('jspdf')

    const doc     = new jsPDF({ unit: 'mm', format: 'a4' })
    const pageW   = doc.internal.pageSize.getWidth()
    const pageH   = doc.internal.pageSize.getHeight()
    const margin  = 20
    const usableW = pageW - margin * 2

    function drawPageHeader() {
      doc.setFillColor(26, 46, 82)
      doc.rect(0, 0, pageW, 16, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.text('EPFO PF Claim Pre-Validator', margin, 11)
      doc.setTextColor(15, 23, 42)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
    }

    function drawPageFooter(pageNum, total) {
      doc.setFontSize(7.5)
      doc.setTextColor(150)
      doc.text(
        'DRAFT — Generated by AI tool for reference only. Verify all details before submitting to EPFO.',
        margin, pageH - 8, { maxWidth: usableW - 25 }
      )
      doc.text(`${pageNum} / ${total}`, pageW - margin, pageH - 8, { align: 'right' })
    }

    // Draw watermark on current page
    function drawWatermark() {
      doc.setTextColor(230, 230, 230)
      doc.setFontSize(52)
      doc.setFont('helvetica', 'bold')
      doc.text('DRAFT', pageW / 2, pageH / 2, { align: 'center', angle: 45 })
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(15, 23, 42)
    }

    drawPageHeader()
    drawWatermark()

    let y = 26
    const lineH = 5.5
    const sectionLineH = 4

    const rawLines = content.split('\n')

    rawLines.forEach(rawLine => {
      // New page if needed
      if (y > pageH - 22) {
        doc.addPage()
        drawPageHeader()
        drawWatermark()
        y = 26
      }

      const trimmed = rawLine.trim()

      // Skip blank disclaimer brackets at top
      if (trimmed.startsWith('[DRAFT DOCUMENT') || trimmed.startsWith('[Verify all')) {
        doc.setFontSize(8)
        doc.setTextColor(160, 80, 0)
        doc.setFont('helvetica', 'italic')
        doc.text(trimmed.replace(/^\[/, '').replace(/\]$/, ''), margin, y)
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        doc.setTextColor(15, 23, 42)
        y += sectionLineH + 1
        return
      }

      // Section separator — a line of dashes
      if (/^-{4,}$/.test(trimmed)) {
        doc.setDrawColor(200, 200, 200)
        doc.line(margin, y, pageW - margin, y)
        y += sectionLineH
        return
      }

      // Blank line
      if (!trimmed) {
        y += 3
        return
      }

      // ALL CAPS headings (section titles)
      const isHeading = trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !/^\d+\./.test(trimmed)
      if (isHeading) {
        if (y > pageH - 30) { doc.addPage(); drawPageHeader(); drawWatermark(); y = 26 }
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        const wrapped = doc.splitTextToSize(trimmed, usableW)
        wrapped.forEach(l => { doc.text(l, margin, y); y += lineH })
        doc.setFont('helvetica', 'normal')
        y += 1
        return
      }

      // Normal text — split to fit width
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      const wrapped = doc.splitTextToSize(rawLine, usableW)
      wrapped.forEach(l => {
        if (y > pageH - 22) { doc.addPage(); drawPageHeader(); drawWatermark(); y = 26 }
        doc.text(l, margin, y)
        y += lineH
      })
    })

    // Add footers to all pages
    const total = doc.internal.getNumberOfPages()
    for (let i = 1; i <= total; i++) {
      doc.setPage(i)
      drawPageFooter(i, total)
    }

    doc.save(filename)
    return true
  } catch (err) {
    console.error('[pdfGenerator] error:', err)
    return false
  }
}
