/**
 * Test: Document generation and print
 *
 * Verifies that documents are generated and the modal opens,
 * and that the print button is present and interactive.
 */
import { test, expect } from '@playwright/test'

async function loginAndRunValidation(page, uan) {
  await page.goto('/login')
  await page.locator('#uan-input').fill(uan)
  await page.locator('#password-input').fill('Demo@1234')
  await page.getByRole('button', { name: /Login/i }).click()
  await page.waitForURL('**/dashboard')

  await page.goto('/claim')
  await page.getByText('Full Withdrawal', { exact: false }).first().click()
  await page.waitForTimeout(300)

  await page.goto('/validate')
  await page.waitForSelector('[data-status="COMPLETE"], .validation-summary', { timeout: 30000 })
}

test.describe('Document generation', () => {
  test('Joint Declaration button opens modal for name-mismatch user', async ({ page }) => {
    await loginAndRunValidation(page, '100673291847') // Ramesh — name mismatch
    await page.goto('/resolution')

    const docBtn = page.getByRole('button', { name: /Download Joint Declaration/i })
    await expect(docBtn).toBeVisible({ timeout: 10000 })
    await docBtn.click()

    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible({ timeout: 15000 })
    await expect(page.getByText(/Joint Declaration/i).first()).toBeVisible()
  })

  test('Document modal has Download PDF and Print buttons', async ({ page }) => {
    await loginAndRunValidation(page, '100673291847')
    await page.goto('/resolution')

    const docBtn = page.getByRole('button', { name: /Download Joint Declaration/i })
    await expect(docBtn).toBeVisible({ timeout: 10000 })
    await docBtn.click()

    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 15000 })
    await expect(page.getByRole('button', { name: /Download PDF/i })).toBeVisible()
    await expect(page.getByRole('button', { name: /Print/i })).toBeVisible()
  })

  test('Document modal closes on Escape key', async ({ page }) => {
    await loginAndRunValidation(page, '100673291847')
    await page.goto('/resolution')

    const docBtn = page.getByRole('button', { name: /Download Joint Declaration/i })
    await expect(docBtn).toBeVisible({ timeout: 10000 })
    await docBtn.click()

    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 15000 })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toBeHidden({ timeout: 5000 })
  })

  test('Document modal closes on Close button', async ({ page }) => {
    await loginAndRunValidation(page, '100673291847')
    await page.goto('/resolution')

    const docBtn = page.getByRole('button', { name: /Download Joint Declaration/i })
    await expect(docBtn).toBeVisible({ timeout: 10000 })
    await docBtn.click()

    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 15000 })
    await page.getByRole('button', { name: /Close/i }).first().click()
    await expect(page.getByRole('dialog')).toBeHidden({ timeout: 5000 })
  })

  test('Document content includes disclaimer text', async ({ page }) => {
    await loginAndRunValidation(page, '100673291847')
    await page.goto('/resolution')

    const docBtn = page.getByRole('button', { name: /Download Joint Declaration/i })
    await expect(docBtn).toBeVisible({ timeout: 10000 })
    await docBtn.click()

    await expect(page.getByRole('dialog')).toBeVisible({ timeout: 15000 })
    await expect(page.getByText(/DRAFT DOCUMENT|generated by AI/i).first()).toBeVisible()
  })
})
