export const CHECK_STATUS = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  PASS: 'PASS',
  FAIL: 'FAIL',
  ADVISORY: 'ADVISORY',
}

export const RESOLUTION_TYPE = {
  JOINT_DECLARATION: 'JOINT_DECLARATION',
  EMPLOYER_ACTION: 'EMPLOYER_ACTION',
  BANK_REVERIFICATION: 'BANK_REVERIFICATION',
  DOB_CORRECTION: 'DOB_CORRECTION',
  NO_ACTION: 'NO_ACTION',
}

export const SCENARIO = {
  NAME_MISMATCH_INITIAL: 'NAME_MISMATCH_INITIAL',
  EMPLOYER_EXIT_AND_BANK_KYC: 'EMPLOYER_EXIT_AND_BANK_KYC',
  ALL_CLEAR: 'ALL_CLEAR',
}
